channels:
  - conda-forge
dependencies:
  - python=3.10
  - setuptools=75.8.2
  - lammps=2023.08.02=*openmpi*
  - fitsnap3=3.1.0
  - matplotlib=3.10.1
  - numpy=1.25.0
  - pandas=2.0.2
  - pytables=3.10.1
  - scipy=1.11.0
  - nbformat=5.9.2
  - jupyter=1.0.0
  - ase=3.24.0
